version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    links:
      - "web"
    depends_on:
      - web
    ports:
     - "8051:8051"
    volumes: ['./app:/app']
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    command: celery -A 'tasks' worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery-queue:/queue']
  monitor:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    depends_on:
      - redis
      - worker
    volumes: ['./celery-queue:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  # redisinsight:
  #   image: 'redislabs/redisinsight:latest'
  #   ports:
  #     - '8001:8001'