version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
     - "5001:5001"
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./app.py
    depends_on:
      - redis
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    links:
      - "web"
      - "worker"
    depends_on:
      - web
      - worker
    ports:
     - "8051:8051"
  # volumes: ['./api:/api']
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    command: celery -A 'tasks' worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
  #   volumes: ['./celery-queue:/queue']
  monitor:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  celery -A 'tasks' flower --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
  #   volumes: ['./celery-queue:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"