FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    tesseract-ocr-eng \
    python3 \
    python3-pip \
    libtesseract-dev \
    zlib1g-dev \
    libgl1-mesa-glx

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV HOST 0.0.0.0
ENV PORT 5001
ENV DEBUG true

COPY . /api
WORKDIR /api

RUN pip3 install Pillow
RUN pip3 install -r requirements.txt

EXPOSE 5001

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5001"]